projectceladon/kernelflinger

Android.mk
if BOARD_AVB_ENABLE isn't set, libavb do not need to be built
Tracked-On: OAM-88398
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>
=> kf4cic: do not build libavb if BOARD_AVB_ENABLE not set

include/security.h, libkernelflinger/security.c, libqltipc/ql-tipc/keymaster.c
Currently the rot data passed to keymaster is not
right. Boot header version is not considered and vbmeta
digest is set to null instead of the actual value.
Tracked-On: OAM-99885
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>
=> Correct the rot data passed to keymaster

libqltipc/interface/include/interface/keymaster/keymaster.h, libqltipc/ql-tipc/include/trusty/keymaster.h, libqltipc/ql-tipc/include/trusty/keymaster_serializable.h, libqltipc/ql-tipc/keymaster.c, libqltipc/ql-tipc/keymaster_serializable.c
Pass boot_patchlevel to trusty.
Boot_patchlevel specifies the kernel image security patch level that must be installed on the device for a key to be used. The value appears in the form YYYYMMDD, representing the date of the system security patch. For example, if a key were generated on an Android device with the system's Oct 1, 2010 security patch installed, this value would be 20101001.
Tracked-On: OAM-99223
Signed-off-by: yuxincui <yuxin.cui@intel.com>
=> Add boot_patchlevel

installer.c
The feature support 3 part files together at least before, cover the file will split into two parts which is
bigger than 4G but less than 8G
such as:
flash super super.img.part01 super.img.part02
Tracked-On: OAM-99747
Signed-off-by: Ai, Ting <ting.a.ai@intel.com>
=> Enhance to support flash two files together

include/security.h, kernelflinger.c, kf4cic.c, libkernelflinger/security.c, libqltipc/interface/include/interface/keymaster/keymaster.h, libqltipc/ql-tipc/include/trusty/keymaster.h, libqltipc/ql-tipc/include/trusty/keymaster_serializable.h, libqltipc/ql-tipc/keymaster.c, libqltipc/ql-tipc/keymaster_serializable.c
Get attestation_ids from boot config, including brand, device, product, manufacturer and model. Pass attestation_ids to trusty via KM_SET_ATTESTATION_IDS.
Tracked-On: OAM-100070
Signed-off-by: yuxincui <yuxin.cui@intel.com>
=> Add implementation of attestation ids in the bootloader

include/trusty_common.h, libkernelflinger/android.c, libkernelflinger/trusty_common.c
Add new function trusty_late_init() which is called between
ExitBootService() and kernel jumping.
Currently, only activate_vtd_vmcall() is called in trusty_late_init().
Tracked-On: OAM-101009
Signed-off-by: Yadong Qi <yadong.qi@intel.com>
=> bm: trigger vmcall to activate VT-d in eVMM

libefiusb/device_mode/XdciDWC.c
Previously there is a patch to handle this kind of issue,
but that patch didn't consider all the scenarios where this
kind of issue may happen.
Tracked-On: OAM-103641
Signed-off-by: jizhenlo <zhenlong.z.ji@intel.com>
=> Check the value of EpNum before accessing the EpHandles

installer.c, libfastboot/Android.mk, libfastboot/installer_ui.c, libfastboot/installer_ui.h
If you use PC to burn the ISO image to USB stick,
and forget to plug out the USB stick from PC,
then reboot your PC with USB stick plugged.
Celadon ISO image will be installed to the PC
automatically without notification. Thus it will
damage the data in your PC.
So we add UI to ask the user to confirm if continue or stop flashing celadon images to this device to avoid data damage.
Tracked-On: OAM-103788
=> Add interaction UI to installer application

libfastboot/fastboot_flashing.c
Stored rollback slots should be removed when status changes during fastboot flash scenario.
Tracked-On: OAM-110759
=> fastboot: Erase stored rollback slots when status changes.

libfastboot/fastboot_flashing.c
This reverts commit 7de1dfc60bd91e13ba7964b01812959b7726e50a as adb reboot/factory reset results in longer boot time.
Tracked-On: OAM-111128
=> Revert "fastboot: Erase stored rollback slots when status changes."

kernelflinger.c
Build kernelfliner as fb4sbl.elf file to support fastboot features
Tracked-On: OAM-111239
=> Force kernelflinger to enter into fastboot mode

libfastboot/fastboot.c, libfastboot/flash.c
If the bootloader partition is NON EFI System partition, perform "safe flash procedure" is not required. Because for NON-EFI, it can't leverage UEFI runtime service to verify new flashed image
Tracked-On: OAM-111722
=> Perform a normal flash for bootloader or bootloader_a/b partition

libkernelflinger/ivshmem.c
Fix the following error while compiling installer: error: cast to 'void *' from smaller integer type 'unsigned int'.
Tracked-On: OAM-112948
=> Fix installer compiling error in ivshmem

include/vars.h, libkernelflinger/android.c, libkernelflinger/vars.c
We will pass ACRN cmdline from SBL to OS.
Any parameter passing from cmd_for_kernel, like cmd_for_kernel=key1=value\\key2=value2 \\key3=value3 will be passed without any check as
key1=value1 key2=value2 key3=value3
Tracked-On: OAM-113545
=> pass ACRN cmdline parameter from sbl to os

libkernelflinger/vars.c
Pass the whole serial number to avoid conflict.
Tracked-On: OAM-113638
=> Fix size mismatch in snprintf for serialno, add a missing bit

include/lib.h, libadb/adb_socket.c, libkernelflinger/lib.c
memcpy_s will report BAD_BUFFER_SIZE when source is NULL. That prevents developers from pulling the entire ram under Crashmode. This patch add a less secury function memcopy_less_s. This function just print a warning message instead of reporting an error when source is NULL.
Tracked-On: OAM-110650
=> Add a memdump function without check for NULL source to pull whole ram

kernelflinger.c, libkernelflinger/android.c, libkernelflinger/android_vb2.c
1. Some functions are useless in the bootloader running on SBL, remove these functions.
2. dummy ACPI occupies 4096 bytes, and there is no data in this dummy ACPI table. However, this dummy ACPI will overwrite other ACPI region and may result in a boot failure. To fix this issue, skip install dummy ACPI table.
Test done: Device can boot up after the OTA.
Tracked-On: OAM-115179
=> Skip install dummy acpi table and remove some unused functions

libfastboot/fastboot.c
If device meets EFI_DEVICE_ERROR while getting USB_REQ_GET_STATUS request from host. This USB error can't recover if re-init USB device. Thus all fastboot functions can't work. We need restart fastboot in case of such failure
Test Done:
fastboot can work after running 400 times below commands: fastboot reboot bootloader
fastboot devices
Tracked-On: OAM-115637
=> Restart fastboot if gets transport run error

kernelflinger.c
Firmware will pass reset reason/boot_target/Version/silent information through commmand line to kernelflinger. Kernelflinger should process these command to enter into required mode or pass the information to Android
Tracked-On: OAM-117246
=> Define interface between firmware and kernelflinger

kernelflinger.c
Androidboot paramaters will be passed to bootconfig, Others pass to kernel cmdline
Tracked-On: OAM-117279
=> Pass firmware parameters to OS

avb/libavb/avb_cmdline.c
When resolved_hashtree_error_mode is unexpected value, abort the program to avoid uninitialized pointer read.
Tracked-On: OAM-118501
=> Fix static scan issues

libkernelflinger/lib.c
Call pause_us() to sleep 1S doesn't take effect, the reason is that multiply overflow
Tracked-On: OAM-120825
=> Solve the 32-bit Integer Multiplication Overflow Issue

kernelflinger.c
test done: boot
Tracked-On: OAM-123665
=> Make device as unlocked state by default on userdebug build for civ

include/adb.h, include/tcp.h, include/transport.h, include/usb.h, kf4abl.c, libadb/adb.c, libefitcp/tcp.c, libefiusb/protocol/UsbDeviceModeProtocol.h, libefiusb/usb.c, libfastboot/fastboot.c, libtransport/transport.c, ux.c
If there is no USB connection in bootloader fastboot mode, device should enter to normal mode after timeout.
Test Done:
Boot, flash, boot to normal mode after USB timeout
Tracked-On: OAM-123898
=> Boot device to normal mode if no USB connection

include/ivshmem.h, include/lib.h, include/qnx_guest_shm.h, libkernelflinger/android.c, libkernelflinger/ivshmem.c, libkernelflinger/lib.c
On QNX platform, kernelflinger can sync with OPTEE by using qnx vdev shm mechanism.
Tracked-On: OAM-123671
=> Add QNX vdev shm support

libadb/reader.c, libefiusb/device_mode/UsbDeviceMode.c, libfastboot/bootmgr.c, libkernelflinger/vars.c, libsslsupport/wrapper.c
Addressed high priority coverity issues related to Memory corruptions, Uninitialized variables
and Memory illegal accesses.
Test done:
Build and boot android success.
Tracked-On: OAM-122325
=> coverity fix for Boot in kernelflinger

libkernelflinger/android.c, libkernelflinger/tpm2_security.c
Get efiwrapper start point time and pass to android
The purpuse is reporting every stage of kernelflinger
exection time to android. It will be convenient to measure
performance data and track regression
=>  Get efiwrapper start point time and pass to android

libfastboot/bootmgr.c, libkernelflinger/fatfs/source/ff.c
Addressed high priority coverity issues related toi Uninitialized variables.
Test done:
Build and boot android success.
Tracked-On: OAM-124618
=> coverity issue fix for Boot in kernelflinger

installer.c, libfastboot/flash.c, libkernelflinger/ui.c, libkernelflinger/ui_textarea.c
Addressed Medium priority coverity issues related to Explicit null dereferenced & integer overflow
Test done:
Build and boot android success.
Tracked-On: OAM-122118
=> Med-coverity issue fix for Boot in kernelflinger

libkernelflinger/android.c
This patch increases the jump time from bootloader and number of tries to a decent number since Celadon boot with coreboot is causing timing issue.
Tests Done: Build and flash and boot on MTL REX board with coreboot
Tracked-On: NA
=> Increase the jump time and try

libkernelflinger/storage.c
Partition offset should be added
Test Done:
fastboot oem setvm <vm_partition>
fastboot erase metadata
fastboot erase userdata
fastboot oem unsetvm
Tracked-On: OAM-126214
=> Sovle failure while earsing a GPT partition of VM through fastboot

libfastboot/fastboot.c
The command is required by fastboot client
Test Done:
1. Enter bootloader mode: adb reboot bootloader
2. reboot bootloader: fastboot reboot bootloader
3. bootloader will reboot
Tracked-On: OAM-111865
=> Support fastboot reboot bootloader command

include/timer.h, libkernelflinger/android.c, libkernelflinger/timer.c
TSC is consistant while cpu freq are dynamically, so use TSC to get boot time is more percisely
Test Done:
boot
Tracked-On: OAM-128926
=> Use TSC to obtain boot performance data

libsslsupport/Android.mk
Observed build error due to missing multiple crypto sources reference. Adding crypto sources.
Tests done: Prepared EB and there is no build error.
Tracked-On: OAM-127806
=> BSP_DIFF cleanup

libfastboot/fastboot.c
Solve android can't endter fastboot mode issue
Cpu freq value cannot be 0, else it will reboot
before it detect usb device mode
Test done:
boot
Tracked-On: OAM-130531
=> Use cpuid to get cpu freqency

crashdump.c, include/android.h, installer.c, kernelflinger.c, libfastboot/fastboot_flashing.c, libkernelflinger/storage.c
In user build, device can't be unlock if unlock_ability is failue. unlock_ablility can be set via developer settings.
Tracked-On: OAM-127732
=> Support userbuild parameter for security

include/android.h, kernelflinger.c, libfastboot/fastboot_ui.c, libkernelflinger/android.c
Support UI display for boot reason
Test Done:
Boot
Tracked-On: OAM-132083
=> Display boot reason in fastboot UI

libkernelflinger/android.c
Solve static scan issue
Test Done:
Boot
Tracked-On: OAM-132338
=> Fix potential memory leak
