libkernelflinger/android.c

Tracked-On: OAM-90221
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

fix error checking value

---

libsslsupport/Android.mk

Tracked-On: OAM-88873
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

crypto: add build flags -Werror=format-security -Wa,--noexecstack

---

libkernelflinger/vbmeta_ias.c

Tracked-On: OAM-90353
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

check pointer return from function call

---

installer.c

The feature support 3 part files together at least before, cover the file will split into two parts
such as:
flash super super.img.part01 super.img.part02
Tracked-On: OAM-99747
Signed-off-by: Ai, Ting <ting.a.ai@intel.com>

Enhance to support flash two files together

---

avb/libavb_ab/avb_ab_flow.c
avb/libavb_ab/avb_ab_flow.h
libfastboot/fastboot.c

1. Add some code to support virtual ab ota.
2. Sync some code with bootctrl.
Tracked-On: OAM-100724
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>

support virtual ab ota

---

libfastboot/flash.c

Erase userdata partition only once during each boot

---

installer.c
libfastboot/flash.c
libfastboot/flash.h

Don't erase userdata partition at the first installation

---

libkernelflinger/android.c

Solve issue in command line classification

---

installer.c
libfastboot/flash.c

Reduce flash time for installer.efi
Tracked-On: OAM-103471

Support userdata partition fast erase

---

installer.c

Fix staitc scan issues

---

libfastboot/fastboot.c

Solve no enough memory for string copy issue

---

Android.mk
include/log.h
include/storage.h
kernelflinger.c
libkernelflinger/android.c
libkernelflinger/security_sbl.c
libsslsupport/wrapper.c

1. Add efiwrapper and libpayload library to support SBL
2. Reuse kerneflinger.c for SBL entry
3. Solve compile issues
Tracked-On: OAM-110183

Add SBL support for kernelflinger

---

libfastboot/fastboot_flashing.c

This reverts commit 0dd202a80c7c61a3c7d3c9803e227f1135a61144.
Tracked-On: OAM-110883

Revert "fastboot: Erase stored rollback slots when status changes."

---

libfastboot/fastboot_flashing.c

Stored rollback slots should be removed when status changes during fastboot flashing unlock scenario.
Tracked-On: OAM-111252

fastboot: Erase stored rollback slots when status changes.

---

include/storage.h
kernelflinger.c
libkernelflinger/android.c

Get boot device diskbus from efiwrapper
Tracked-On: OAM-112165

Use get_bootdev_diskbus instead of get_diskbus

---

Android.mk
libkernelflinger/vbmeta_ias.c
libsslsupport/openssl_support.h
libsslsupport/stddef.h

These patches was added during 14 bring-up and was initially put in vendor-intel-utils. Moving it to corresponding repo as a part of clean-up.
Tracked-On: OAM-112683

14 cleanup

---

include/vars.h
libkernelflinger/android.c
libkernelflinger/vars.c

Pass bootreason from SBL to kernel command line
Tracked-On: OAM-112951

Pass bootreason from SBL to kernel command line

---

libkernelflinger/android.c

Support booting from disk not on PCI bridge

---

include/security.h
kernelflinger.c
libkernelflinger/security.c

on optee side, the keymaster ta will bind these information into each user generated keys.
Tracked-On: OAM-113489

OP-TEE: send root of trust via ivshmem driver to optee

---

libedk2_tpm/Tpm2Ptp.c
libedk2_tpm/Tpm2Tis.c

It will reduce the TPM FlushContext failure rate
Tracked-On: OAM-114168

Increase TPM pause value

---

libkernelflinger/tpm2_security.c

Forward lock-tpm2-owner cmd to TEE

---

libkernelflinger/tpm2_security.c

print rollback index info for testing purpose

---

libkernelflinger/android.c

The purpuse is reporting every stage of kernelflinger exection time to android. It will be convenient to measure performance data and track regression
How to use:
adb shell getprop | grep FWS
Test done: boot success
Tracked-On: OAM-115655

Get efiwrapper start point time and pass to android

---

avb/libavb/avb_slot_verify.c
avb/libavb_user/uefi_avb_ops.c
libedk2_tpm/Tpm2Capability.c
libfastboot/fastboot.c
libfastboot/hashes.c
libkernelflinger/android.c
libkernelflinger/gpt.c
libkernelflinger/lib.c
libkernelflinger/oemvars.c
libkernelflinger/slot_avb.c
libsslsupport/wrapper.c

Fix static scan issues

---

kernelflinger.c

Remove battery and charger mode check

---

avb/libavb/avb_slot_verify.c
avb/libavb_user/uefi_avb_ops.c
libedk2_tpm/Tpm2Capability.c
libfastboot/fastboot.c
libfastboot/hashes.c
libkernelflinger/android.c
libkernelflinger/gpt.c
libkernelflinger/lib.c
libkernelflinger/oemvars.c
libkernelflinger/slot_avb.c
libsslsupport/wrapper.c

Fix static scan issues for kernelflinger

---

libkernelflinger/android.c

The old code append abl_cmd_line to the end of cmd_conf. Now we prepand abl_cmd_line to cmd_conf.
Tracked-On: OAM-117889

put SBL parameters to the head of commandline

---

TPP

Test Done: build success
Tracked-On: OAM-123760

Add third-party program for kernelflinger

---

libkernelflinger/android.c

Check if SOS cmdline contains console parameter, if so, check if kernel cmdline contains a console of same type. If so, remove the kernel's console parameter. This patch also change SBL cmdline's position from beginning to the end of cmd_conf.
Tracked-On: OAM-123651

Remove the kernel's console parameter if it’s the same type as SOS command

---

libfastboot/fastboot_flashing.c
libkernelflinger/fatfs/source/ff.c
libkernelflinger/lib.c
libkernelflinger/slot_avb.c
libkernelflinger/vars.c

fix coverity issue for Boot in kernelflinger

---

kernelflinger.c

Get ROT from OPTEE TPM if optee is enabled
Tracked-On: OAM-126574

Get root of trust from tee TPM

---

libadb/reader.c
libfastboot/flash.c
libkernelflinger/fatfs/source/ff.c

Test Done:
boot/reboot several times work normally
Tracked-On: OAM-126533

fix coverity issue for Boot in kernelflinger - 2

---

include/vars.h
libkernelflinger/android.c
libkernelflinger/storage.c
libkernelflinger/vars.c
libsslsupport/wrapper.c

Test Done:
boot
Tracked-On: OAM-129720

fix static scan issue

---

include/lib.h
libadb/ioport.c
libkernelflinger/android.c
libkernelflinger/embedded_controller.c
libkernelflinger/lib.c

On Acrn, warm or cold boot can be get from 0xcf9 port
Test Done:
Boot
Tracked-On: OAM-130882

Get boot reason in a VM env
